query {
    characters(filter: { name: "" }) {
        info {
            count
        }
        results {
            id,
            image,
            name,
            gender,
            species,
            episode {
                episode
            }
        }
    }
}
